---
- name: Launch Database
  docker_container:
    name: my_database
    image: postgres:latest
    env:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
